import { CATEGORY_LABELS } from "../constants.js";

export function renderMarkdown(report) {
  const critical = report.findings.filter((finding) => finding.severity === "critical").length;
  const warnings = report.findings.filter((finding) => finding.severity === "warning").length;
  const fixable = report.findings.filter((finding) => finding.fixable).length;
  const lines = [];

  lines.push(`# Repo Doctor Report: ${report.project.name}`);
  lines.push("");
  lines.push(`Scanned at: ${report.project.scannedAt}`);
  lines.push("");
  lines.push(`**Health Score:** ${report.score}/100`);
  lines.push("");
  lines.push(`**Findings:** ${critical} critical, ${warnings} warnings, ${fixable} fixable suggestions`);
  lines.push("");
  lines.push("## Category Scores");
  lines.push("");
  lines.push("| Category | Score | Findings |");
  lines.push("| --- | ---: | ---: |");

  for (const category of Object.values(report.categories)) {
    lines.push(`| ${category.label} | ${category.score}/100 | ${category.findings} |`);
  }

  lines.push("");
  lines.push("## Top Findings");
  lines.push("");

  if (report.findings.length === 0) {
    lines.push("No issues found. Nice.");
  } else {
    for (const item of report.findings.slice(0, 20)) {
      lines.push(`### ${severityLabel(item.severity)} ${item.title}`);
      lines.push("");
      lines.push(`Category: ${CATEGORY_LABELS[item.category] ?? item.category}`);
      lines.push("");
      lines.push(item.summary);
      lines.push("");
      lines.push(`Recommendation: ${item.recommendation}`);
      lines.push("");

      if (item.evidence.length > 0) {
        lines.push("Evidence:");
        for (const entry of item.evidence) {
          const suffix = entry.detail ? ` - ${entry.detail}` : "";
          lines.push(`- \`${entry.file}:${entry.line}\`${suffix}`);
        }
        lines.push("");
      }
    }
  }

  lines.push("## Strengths");
  lines.push("");

  if (report.strengths.length === 0) {
    lines.push("No strengths were detected by the current ruleset.");
  } else {
    for (const item of report.strengths.slice(0, 12)) {
      lines.push(`- **${item.title}:** ${item.summary}`);
    }
  }

  lines.push("");
  lines.push("## Repository Stats");
  lines.push("");
  lines.push(`- Files scanned: ${report.stats.files}`);
  lines.push(`- Lines scanned: ${report.stats.lines}`);
  lines.push(`- Bytes scanned: ${report.stats.bytes}`);
  lines.push("");

  if (report.stats.languages.length > 0) {
    lines.push("### Languages");
    lines.push("");
    lines.push("| Language | Files | Lines |");
    lines.push("| --- | ---: | ---: |");
    for (const language of report.stats.languages.slice(0, 10)) {
      lines.push(`| ${language.language} | ${language.files} | ${language.lines} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("Generated by Repo Doctor.");
  lines.push("");

  return lines.join("\n");
}

function severityLabel(severity) {
  if (severity === "critical") {
    return "[critical]";
  }
  if (severity === "warning") {
    return "[warning]";
  }
  return "[info]";
}
