export function renderUnderstandingMarkdown(report) {
  const understanding = report.understanding;
  const lines = [`# Repository Overview: ${report.project.name}`, ""];

  if (!understanding) {
    lines.push("Repository Understanding data is not available in this report.", "");
    return lines.join("\n");
  }

  lines.push(understanding.summary.text);
  lines.push("");
  lines.push(`Basis: **${understanding.summary.basis}**`);
  appendEvidence(lines, understanding.summary.evidence);

  lines.push("## Confirmed Facts", "");
  for (const fact of understanding.facts) {
    lines.push(`- **${fact.label}:** ${fact.value} _(${fact.basis})_`);
  }
  lines.push("");

  lines.push("## Main Capabilities", "");
  if (understanding.capabilities.length === 0) {
    lines.push("No capabilities were stated clearly enough to extract without guessing.");
  } else {
    for (const item of understanding.capabilities) {
      lines.push(`- ${item.text} _(${item.basis})_`);
      appendInlineEvidence(lines, item.evidence);
    }
  }
  lines.push("");

  lines.push("## How To Run", "");
  if (understanding.runInstructions.length === 0) {
    lines.push("No reliable run command was found in README or project configuration.");
  } else {
    for (const item of understanding.runInstructions) {
      lines.push(`- \`${item.command}\` - ${item.source}`);
      appendInlineEvidence(lines, item.evidence);
    }
  }
  lines.push("");

  lines.push("## Core Files", "");
  if (understanding.coreFiles.length === 0) {
    lines.push("No core files could be identified confidently.");
  } else {
    lines.push("| File | Likely role | Basis |");
    lines.push("| --- | --- | --- |");
    for (const item of understanding.coreFiles) {
      lines.push(`| \`${item.path}\` | ${item.role} | ${item.basis} |`);
    }
  }
  lines.push("");

  lines.push("## Possible Gaps", "");
  if (understanding.likelyGaps.length === 0) {
    lines.push("No gaps were identified by the current ruleset.");
  } else {
    for (const gap of understanding.likelyGaps) {
      lines.push(`- **[${gap.severity}] ${gap.title}:** ${gap.reason}`);
    }
  }
  lines.push("");
  lines.push(`> ${understanding.limits}`);
  lines.push("");
  lines.push("Generated by Repo Doctor from repository evidence.");
  lines.push("");

  return lines.join("\n");
}

function appendEvidence(lines, evidenceItems = []) {
  if (evidenceItems.length === 0) {
    lines.push("");
    return;
  }
  lines.push("");
  lines.push("Evidence:");
  for (const entry of evidenceItems) {
    lines.push(`- \`${entry.file}:${entry.line}\`${entry.detail ? ` - ${entry.detail}` : ""}`);
  }
  lines.push("");
}

function appendInlineEvidence(lines, evidenceItems = []) {
  for (const entry of evidenceItems.slice(0, 1)) {
    lines.push(`  Evidence: \`${entry.file}:${entry.line}\`${entry.detail ? ` - ${entry.detail}` : ""}`);
  }
}
